version: "3"
services:
    db:
        image: mariadb:10
        volumes:
            - mariadb-datavolume:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%

volumes:
  mariadb-datavolume:
